### ISSUE TITLE
Invalid private key reconstructed from shares

### ISSUE THREAD

**Issue by joe-pellegrino** [thirdweb-example/expo-starter#2]
This error is triggered by either immediately after authenticating with social, or entering a OTP via email.

 ERROR  Error setting up wallet on device [Error: Invalid private key reconstructed from shares]
 ERROR  Error while signing in with: Google. Error: Malformed response from post authentication: Invalid private key reconstructed from shares
 ERROR  [Error: Error signing in with Google: Malformed response from post authentication: Invalid private key reconstructed from shares]

**Comment by joaquim-verges** [comment]
thanks @joe-pellegrino ! I just pushed a fix for this in the sdk and pushed the latest in the expo-starter. 

Can you pull latest and try again?

**Comment by joe-pellegrino** [comment]
> thanks @joe-pellegrino ! I just pushed a fix for this in the sdk and pushed the latest in the expo-starter.
> 
> Can you pull latest and try again?

Looks like its fixed, I tried social and email auth as well. 

Thanks!
