### ISSUE TITLE
Error running: npx thirdweb create app --expo

### ISSUE THREAD

**Issue by sparkle666** [thirdweb-example/expo-starter#8]
@joaquim-verges  

Need to install the following packages:
thirdweb@5.31.0
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: thirdweb@5.29.0
npm ERR! node_modules/thirdweb
npm ERR!   thirdweb@"5.31.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! thirdweb@"5.31.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.2.0" from react-native@0.74.2
npm ERR!   node_modules/react-native
npm ERR!     peerOptional react-native@">=0.70" from thirdweb@5.31.0
npm ERR!     node_modules/thirdweb
npm ERR!       thirdweb@"5.31.0" from the root project
npm ERR!     peer react-native@"*" from @coinbase/wallet-mobile-sdk@1.0.13
npm ERR!     node_modules/@coinbase/wallet-mobile-sdk
npm ERR!       peerOptional @coinbase/wallet-mobile-sdk@"^1" from thirdweb@5.31.0
npm ERR!       node_modules/thirdweb
npm ERR!         thirdweb@"5.31.0" from the root project
npm ERR!     2 more (@react-native-async-storage/async-storage, react-native-aes-gcm-crypto)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/chinemerem/.npm/_logs/2024-06-30T15_02_07_301Z-eresolve-report.txt

**Comment by joaquim-verges** [comment]
can you try this?

`npm config -g set legacy-peer-deps true`

then run `npx thirdweb create` again

**Comment by sparkle666** [comment]
Yeah it works but expo returned:
![IMG_20240701_072930](https://github.com/thirdweb-example/expo-starter/assets/45319713/0bd49b83-9afb-4695-baf1-c63aeaa0ade5)

So removed the --expo and it worked and had to choose which dev tool I wanted which is react native.
